/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EpFacebook: typeof import('~icons/ep/facebook')['default']
    EpGithub: typeof import('~icons/ep/github')['default']
    EpGoogle: typeof import('~icons/ep/google')['default']
    EpLocation: typeof import('~icons/ep/location')['default']
    EpLock: typeof import('~icons/ep/lock')['default']
    EpMenu: typeof import('~icons/ep/menu')['default']
    EpMoon: typeof import('~icons/ep/moon')['default']
    EpOperation: typeof import('~icons/ep/operation')['default']
    EpRefresh: typeof import('~icons/ep/refresh')['default']
    EpSunny: typeof import('~icons/ep/sunny')['default']
    EpTwitter: typeof import('~icons/ep/twitter')['default']
    EpUserFilled: typeof import('~icons/ep/user-filled')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
